# pulling list of filenames generated by password creator

$maillist = Get-ChildItem -Path "C:\temp\*.txt" -Name

foreach ($server in $maillist) {
    
    $mailserver = $server.TrimEnd(".txt")

    # Retrieving Password

    $pwdTxt = Get-Content "C:\temp\$mailserver.txt"
    $securePwd = $pwdTxt | ConvertTo-SecureString
    $credObject = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $securePwd)
    $password = $credObject.GetNetworkCredential().Password
    $username = $credObject.GetNetworkCredential().UserName
    
    # SM Authentication

    $authHeaders = New-Object "System.collections.Generic.Dictionary[[String],[String]]"
    $authHeaders.Add("Content-Type", "application/json")

    $authBody = "{ `n	`"username`": `"$username`",`n	`"password`": `"$password`" `n}"

    $response = Invoke-RestMethod "http://$mailserver/api/v1/auth/authenticate-user" -Method 'POST' -Headers $authHeaders -Body $authBody

    # SM Access Token

    $smailAuthRes = $response.accessToken

    # Message Traffic Statistics Example

    $statHeaders = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
    $statHeaders.Add("Authorization", "Bearer $smailAuthRes")

    $stats = Invoke-RestMethod "http://$mailserver/api/v1/settings/sysadmin/message-traffic-statistics" -Method 'GET' -Headers $statHeaders
}


